### ISSUE TITLE
TestTime::test_init_timeseries failure on windows

### ISSUE THREAD

**Issue by jdhughes-usgs** [EC-USGS/pynhm#58]
Failure is intermittent on Windows. Made some attempts to fix but did not resolve the issue. Does not seem to fail when run in serial but occasionally fails when run in parallel.

**Comment by jmccreight** [comment]
I believe i fixed this in a future PR for snow
https://github.com/jmccreight/pynhm/commit/bb733c2fa79bdd06fb37605629a6640fff588b43

**Comment by jmccreight** [comment]
it required a deepcopy. i could actually reproduce this on mac. it's mysterious why linux and mac didnt throw errors

**Comment by jmccreight** [comment]
The solution might be better if Time deepcopies the data. I didnt fully assess that, i just wanted the problem solved which it appears to have been. I think Time will be revisited before long with a proper solution. So you dont have to wait on me, you can just use the first and last line with deepcopy. The middle line is an errant comment from when I tried using fixture scope instead of deepcopy.

**Comment by jmccreight** [comment]
Zerothly, pull out the head bandages 🤕, this is really strange and convoluted. I dont know why the behavior seemingly changed and the code didnt. But several things seem to be happening at once. I have a coherent explanation based on local testing but CI seems to be at odds on mac and linux. Will kind of leave that aside

I guess first thing is first... is this the error to which you refer?

https://github.com/jmccreight/pynhm/runs/5846297732?check_suite_focus=true#step:9:503
which is in the output here: 
https://github.com/jmccreight/pynhm/runs/5846297732?check_suite_focus=true#step:9:290

So, I can reproduce this on a mac with no code changes by doing 
```
pytest -s -vv -n=auto  test_base.py::TestTime::test_init_timeseries
```

that's strange by itself cause the same thing dosent seemingly fail in CI. But if I turn off parallel, then it passes.

(leaving CI alone and talking about local runs) I believe I see why this is happening and it should fail. I believe parallel is helping solve one of the two problems which is this line:
` time["datetime"] += np.timedelta64(24, "h")`
even though it seems to fail to set, the operator still modifies the global time_data. When run in serial, that change affects subsequent tests. When run in parallel, test_data apparently gets copied to separate processes and is not modified in subsequent tests. 

If the time_data is modified by adding 24hrs then the other indexing error in the test dosent occur. When the test is run in parallel, the indexing error occurs. That indexing error is a mistake in the test construction: 

`start_times = [time_data[0], time_data[3], np.datetime64(datetime(1980, 1, 1))]`

the middle entry is the last time of the timeseries when run in parallel (which can not advance) but when run in serial it becomes the second to last entry (which can advance).

I suppose the lesson is *"dont use global data for parallel tests"*. The modify of the global data is a bit of a sneaker in this case because the value setting should fail (though this might be considered a bug in StateAccess, but it's unclear and apparently has to do with how `+=` is implemented). So the test is if modifying global variable is turned off: then the serial test should fail. Deepcopy provides that "fix" to fail. Alternatively, copy on modify can be employed with the long hand for `+=` and then deepcopy is not necessary. I think a pytest fixture for the test data with function scope is probably the correct solution here and the lesson is try to avoid global data. In that case, the entries in start_times probably have to be hard-coded and not referenced against `time_data`.

This is a middle ground solution where the global data is used in a fixture
```
diff --git a/autotest/test_base.py b/autotest/test_base.py
index 3069678..de8e728 100644
--- a/autotest/test_base.py
+++ b/autotest/test_base.py
@@ -80,11 +80,21 @@ class TestStateAccess:
         return
 
 
-time_data = np.arange(
+time_data_global = np.arange(
     datetime(1979, 1, 1), datetime(1979, 1, 5), timedelta(days=1)
 ).astype(np.datetime64)
 
-start_times = [time_data[0], time_data[3], np.datetime64(datetime(1980, 1, 1))]
+
+@pytest.fixture(scope="function")
+def time_data():
+    return time_data_global
+
+
+start_times = [
+    time_data_global[0],
+    time_data_global[3],
+    np.datetime64(datetime(1980, 1, 1)),
+]
 time_step = np.timedelta64(24, "h")
 time_ids = ("valid0", "valid1", "invalid")
 
@@ -124,10 +134,12 @@ class TestTime:
         start_times,
         ids=time_ids,
     )
-    def test_init_timeseries(self, start_time):
+    def test_init_timeseries(self, start_time, time_data):
```
Without modifying the index, it results in the desired failure for a serial run. 

Then I can modify the second entry in `start_times` to be `time_data[2]`. 

The result is #59. Sorry for the brain damage!
